"""
Django settings for EcoIntercambio_ProyectoIntegracion project.

Generated by 'django-admin startproject' using Django 5.0.4.
"""

from pathlib import Path
import os
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!ge_o@w7tp4yvir#bs-b5^^xmd2yb8ba^7^5oc5qofip^yj7s1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Para desarrollo/local
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Evita ventanas en blanco con el popup de PayPal en algunos navegadores
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

WSGI_APPLICATION = 'EcoIntercambio_ProyectoIntegracion.wsgi.application'
ASGI_APPLICATION = 'EcoIntercambio_ProyectoIntegracion.asgi.application'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'app',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.humanize',
    'channels',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcoIntercambio_ProyectoIntegracion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "app.context_processors.subscription_context",
            ],
        },
    },
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'DB_Eco',
        'USER': 'root',
        'PASSWORD': '',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'app/static')]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================  PAYPAL / SUSCRIPCIÓN  (SANDBOX)  =====================

# Tu Client ID sandbox (el que me pasaste)
PAYPAL_CLIENT_ID = "AbXfmAS2trfOMc3o4tvD2IlFkHt7rQUh81BcSGuIaxXv3KNYCIjprHDiIvYBt2QZZ60xrrWvA3ScbfbD"

# Tu Secret sandbox (el que me pasaste)
PAYPAL_CLIENT_SECRET = "EOtrpFdlZRnoC-rLb_P86VrHvSK_SIJpQCJkcVCtKQrtszb6pX0YkDD0z1fQVuUfXe1bOwm9c4DV-v4W"

# Ambiente sandbox (para producción será "live")
PAYPAL_ENV = "sandbox"
from decimal import Decimal
# Precio y moneda: en sandbox usa USD para evitar popup en blanco
SUBSCRIPTION_PRICE = Decimal("1.58")   # 2000 USD de prueba (solo sandbox)
SUBSCRIPTION_CURRENCY = "USD"
SUBSCRIPTION_DESCRIPTION = "Suscripción mensual a EcoIntercambio"
