"""
Django settings for EcoIntercambio_ProyectoIntegracion project.

Generated by 'django-admin startproject' using Django 5.0.4.
"""

from pathlib import Path
import os
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-!ge_o@w7tp4yvir#bs-b5^^xmd2yb8ba^7^5oc5qofip^yj7s1')

# SECURITY WARNING: don't run with debug turned on in production!
# Obtiene el valor de DEBUG de Azure; si no existe, asume 'False' por seguridad.

# Para desarrollo/local
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "ecointercambio.azurewebsites.net",
    "ecointercambio-docker.azurewebsites.net",
    "*",
]


# Evita ventanas en blanco con el popup de PayPal en algunos navegadores
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

WSGI_APPLICATION = 'EcoIntercambio_ProyectoIntegracion.wsgi.application'
ASGI_APPLICATION = 'EcoIntercambio_ProyectoIntegracion.asgi.application'

# Application definition
INSTALLED_APPS = [
    'app.apps.AppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.humanize',
    'channels',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'EcoIntercambio_ProyectoIntegracion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "app.context_processors.subscription_context",
            ],
        },
    },
]

# Detecta si estás en Render o local
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"
IS_RENDER = os.environ.get("RENDER", None) is not None

REDIS_URL = os.environ.get(
    "REDIS_URL",
    "redis://default:6cdhZNG0hS63PMod4U84gIpq1qAIYakz@redis-11399.c241.us-east-1-4.ec2.redns.redis-cloud.com:11399"
)


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}


import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

USE_AZURE_DB = os.environ.get('USE_AZURE_DB') == 'True'
USE_RENDER_DB = os.environ.get('USE_RENDER_DB') == 'True'
USE_LOCAL_MYSQL = os.environ.get('USE_LOCAL_MYSQL') == 'True'


# Variables de entorno para activar la base correspondiente
USE_AZURE_DB = os.environ.get('USE_AZURE_DB') == 'True'
USE_RENDER_DB = os.environ.get('USE_RENDER_DB') == 'True'
USE_LOCAL_MYSQL = os.environ.get('USE_LOCAL_MYSQL') == 'True'


if USE_AZURE_DB:
    print("✅ Usando base de datos: Azure MySQL")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('AZURE_MYSQL_NAME'),
            'USER': os.environ.get('AZURE_MYSQL_USER'),
            'PASSWORD': os.environ.get('AZURE_MYSQL_PASSWORD'),
            'HOST': os.environ.get('AZURE_MYSQL_HOST'),
            'PORT': '3306',
            'OPTIONS': {
                'ssl': {
                    'ca': os.path.join(BASE_DIR, 'DigiCertGlobalRootG2.crt.pem')
                }
            }
        }
    }

elif USE_RENDER_DB:
    print("✅ Usando base de datos: Render PostgreSQL")
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }

elif USE_LOCAL_MYSQL:
    print("✅ Usando base de datos: MySQL local")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'DB_Eco',
            'USER': 'root',
            'PASSWORD': '',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }

else:
    print("⚠️ Usando base de datos SQLite (por defecto)")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'app/static')]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# ✅ Activa WhiteNoise para servir archivos comprimidos
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SMTP Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER


# =====================  PAYPAL / SUSCRIPCIÓN  (SANDBOX)  =====================

from decimal import Decimal

PAYPAL_ID = "AbXfmAS2trfOMc3o4tvD2IlFkHt7rQUh81BcSGuIaxXv3KNYCIjprHDiIvYBt2QZZ60xrrWvA3ScbfbD"
PAYPAL_SECRET = "EOtrpFdlZRnoC-rLb_P86VrHvSK_SIJpQCJkcVCtKQrtszb6pX0YkDD0z1fQVuUfXe1bOwm9c4DV-v4W"

# ===== PayPal SANDBOX =====
PAYPAL_ENV = "sandbox"  # "live" al pasar a producción
PAYPAL_CLIENT_ID = PAYPAL_ID
PAYPAL_CLIENT_SECRET = PAYPAL_SECRET

# ===== Suscripción =====
SUBSCRIPTION_PRICE = Decimal("1.58")       # ≈ 1500 CLP a USD
SUBSCRIPTION_CURRENCY = "USD"
SUBSCRIPTION_DESCRIPTION = "Suscripción Premium EcoIntercambio"

# ✅ CSRF y dominios confiables
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')

CSRF_TRUSTED_ORIGINS = [
    "https://ecointercambio.onrender.com",
    "https://ecointercambio.azurewebsites.net",
    "https://ecointercambio-docker.azurewebsites.net",
]

# Agrega dinámicamente si estás en Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')