# Generated by Django 5.0.4 on 2024-10-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
