# Generated by Django 5.0.4 on 2024-09-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
