# Generated by Django 5.0.4 on 2024-09-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_producto_imagen_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
